# Generated by Django 4.0.4 on 2022-04-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basiskasus',
            name='nama_pasien',
        ),
    ]
