# Generated by Django 4.0.4 on 2022-04-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_basiskasus_nama_pasien'),
    ]

    operations = [
        migrations.AddField(
            model_name='penyakit',
            name='tindakan',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
